name: Sync labels

on:
  workflow_call:
    inputs:
      additional-config:
        description: 'Additional config file in the repo'
        required: false
        type: string

permissions:
  issues: write

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout additional config
        if: ${{ inputs.additional-config }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          sparse-checkout: ${{ inputs.additional-config }}

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: |
            https://raw.githubusercontent.com/Friedinger/Configs/refs/heads/main/conventions/labels.yml
            ${{ inputs.additional-config }}
          delete-other-labels: true
